(async function () {
  "use strict";

  const supported = ["he", "en", "pl", "de", "cs"];
  const requested = new URLSearchParams(location.search).get("lang");
  let language = supported.includes(requested) ? requested : (localStorage.getItem("wroclaw24-language") || "he");
  let activeCategory = "all";
  let searchTerm = "";
  let selectedId = null;

  const ui = {
    he:{brandLine:"מגלים את התרבות של ורוצלב",eyebrow:"המוצר השישי של Wroc-love",title:"ההרפתקה<br>התרבותית.",lead:"מוזיאונים, אמנות, תיאטרון, מוזיקה, קולנוע ואדריכלות — בוחרים תחום ומרכיבים ביקור שמתאים לכם.",places:"מקומות",fiveLanguages:"חמש שפות",directNavigation:"ניווט ישיר",questionLabel:"אין מסלול חובה",question:"מה מסקרן אתכם היום?",questionHint:"בחרו תחום; המפה תציג את המקומות המתאימים ותאפשר לעבור ביניהם בחופשיות.",explore:"לגלות לפי תחום",mapTitle:"מפת התרבות",searchLabel:"חיפוש מקום",searchPlaceholder:"חפשו מקום או תחום…",all:"הכול",museumsHistory:"מוזיאונים והיסטוריה",artContemporary:"אמנות עכשווית",theatre:"תיאטרון ומופע",musicOpera:"מוזיקה ואופרה",film:"קולנוע",architectureDesign:"אדריכלות ועיצוב",streetArt:"אמנות רחוב",mapNote:"המפה מתקרבת לתוצאות. אמנות הרחוב מסומנת בשני פינים אזוריים: Nadodrze ו‑Ołbin.",allPlaces:"כל המקומות והחוויות",emptyTitle:"לא נמצאה התאמה",emptyText:"נסו חיפוש אחר או חזרו להצגת הכול.",showAll:"הציגו הכול",livingGuide:"מדריך שחי ומתעדכן",editorialTitle:"לא מסלול קשיח. אוסף תרבותי שאפשר להרכיב ממנו יום משלכם.",editorialText:"כל כרטיס מפנה לרשומת המקום הקנונית, לאתר הרשמי ולניווט. אמנות הרחוב מוצגת כחוויית שכונות עם שני פינים אזוריים.",homeReturn:"חזרה לאתר הראשי",communityLine:"מבית קהילת Wrocław & Lower Silesia",facebookGroup:"קבוצת הפייסבוק",facebookPage:"הדף העסקי",instagram:"אינסטגרם",navigate:"ניווט",officialWebsite:"אתר רשמי",photos:"תמונות",videos:"וידאו",resultOne:"תוצאה",resultMany:"תוצאות",areaExperience:"חוויית אזור"},
    en:{brandLine:"Discover Wrocław through culture",eyebrow:"The sixth Wroc-love product",title:"The cultural<br>adventure.",lead:"Museums, art, theatre, music, film and architecture — choose a field and shape a visit that suits you.",places:"places",fiveLanguages:"Five languages",directNavigation:"Direct navigation",questionLabel:"No required route",question:"What interests you today?",questionHint:"Choose a field; the map will show matching places and let you move freely between them.",explore:"Explore by field",mapTitle:"The culture map",searchLabel:"Search places",searchPlaceholder:"Search a place or field…",all:"All",museumsHistory:"Museums & history",artContemporary:"Art & contemporary",theatre:"Theatre & performance",musicOpera:"Music & opera",film:"Film",architectureDesign:"Architecture & design",streetArt:"Street art",mapNote:"The map zooms to results. Street art is marked with two area pins: Nadodrze and Ołbin.",allPlaces:"All places and experiences",emptyTitle:"No match found",emptyText:"Try another search or show everything.",showAll:"Show all",livingGuide:"A living, evolving guide",editorialTitle:"Not a fixed route. A cultural collection for building your own day.",editorialText:"Every card uses its canonical Place and links to the official website and navigation. Street art is presented as a neighbourhood experience with two area pins.",homeReturn:"Back to the main site",communityLine:"By the Wrocław & Lower Silesia community",facebookGroup:"Facebook group",facebookPage:"Business page",instagram:"Instagram",navigate:"Navigate",officialWebsite:"Official website",photos:"Photos",videos:"Video",resultOne:"result",resultMany:"results",areaExperience:"Area experience"},
    pl:{brandLine:"Odkrywaj kulturę Wrocławia",eyebrow:"Szósty produkt Wroc-love",title:"Kulturalna<br>przygoda.",lead:"Muzea, sztuka, teatr, muzyka, film i architektura — wybierz dziedzinę i ułóż własną wizytę.",places:"miejsc",fiveLanguages:"Pięć języków",directNavigation:"Bezpośrednia nawigacja",questionLabel:"Bez obowiązkowej trasy",question:"Co ciekawi Cię dzisiaj?",questionHint:"Wybierz dziedzinę; mapa pokaże odpowiednie miejsca i pozwoli swobodnie je łączyć.",explore:"Odkrywaj według dziedziny",mapTitle:"Mapa kultury",searchLabel:"Szukaj miejsca",searchPlaceholder:"Szukaj miejsca lub dziedziny…",all:"Wszystko",museumsHistory:"Muzea i historia",artContemporary:"Sztuka współczesna",theatre:"Teatr i performans",musicOpera:"Muzyka i opera",film:"Film",architectureDesign:"Architektura i design",streetArt:"Street art",mapNote:"Mapa dopasowuje się do wyników. Street art oznaczono dwoma punktami obszarowymi: Nadodrze i Ołbin.",allPlaces:"Wszystkie miejsca i doświadczenia",emptyTitle:"Brak wyników",emptyText:"Spróbuj innego wyszukiwania lub pokaż wszystko.",showAll:"Pokaż wszystko",livingGuide:"Żywy, rozwijany przewodnik",editorialTitle:"Nie sztywna trasa. Zbiór kultury do ułożenia własnego dnia.",editorialText:"Każda karta korzysta z kanonicznego Place i prowadzi do oficjalnej strony oraz nawigacji. Street art to doświadczenie dzielnic z dwoma punktami obszarowymi.",homeReturn:"Wróć do strony głównej",communityLine:"Od społeczności Wrocław & Dolny Śląsk",facebookGroup:"Grupa na Facebooku",facebookPage:"Strona firmowa",instagram:"Instagram",navigate:"Nawigacja",officialWebsite:"Oficjalna strona",photos:"Zdjęcia",videos:"Wideo",resultOne:"wynik",resultMany:"wyników",areaExperience:"Doświadczenie obszaru"},
    de:{brandLine:"Breslaus Kultur entdecken",eyebrow:"Das sechste Wroc-love-Produkt",title:"Das Kultur-<br>abenteuer.",lead:"Museen, Kunst, Theater, Musik, Film und Architektur – Bereich wählen und den eigenen Besuch gestalten.",places:"Orte",fiveLanguages:"Fünf Sprachen",directNavigation:"Direkte Navigation",questionLabel:"Keine Pflichtstrecke",question:"Was interessiert Sie heute?",questionHint:"Bereich wählen; die Karte zeigt passende Orte für eine freie Zusammenstellung.",explore:"Nach Bereich entdecken",mapTitle:"Kulturkarte",searchLabel:"Orte suchen",searchPlaceholder:"Ort oder Bereich suchen…",all:"Alle",museumsHistory:"Museen & Geschichte",artContemporary:"Kunst & Gegenwart",theatre:"Theater & Performance",musicOpera:"Musik & Oper",film:"Film",architectureDesign:"Architektur & Design",streetArt:"Street Art",mapNote:"Die Karte zoomt zu den Ergebnissen. Street Art ist mit zwei Gebietspins markiert: Nadodrze und Ołbin.",allPlaces:"Alle Orte und Erlebnisse",emptyTitle:"Keine Treffer",emptyText:"Andere Suche versuchen oder alles anzeigen.",showAll:"Alle anzeigen",livingGuide:"Ein lebendiger Guide",editorialTitle:"Keine starre Route. Eine Kultursammlung für den eigenen Tag.",editorialText:"Jede Karte nutzt den kanonischen Ort und verlinkt offizielle Website und Navigation. Street Art erscheint als Viertelerlebnis mit zwei Gebietspins.",homeReturn:"Zurück zur Hauptseite",communityLine:"Von der Wrocław & Lower Silesia Community",facebookGroup:"Facebook-Gruppe",facebookPage:"Unternehmensseite",instagram:"Instagram",navigate:"Navigieren",officialWebsite:"Offizielle Website",photos:"Fotos",videos:"Video",resultOne:"Ergebnis",resultMany:"Ergebnisse",areaExperience:"Gebietserlebnis"},
    cs:{brandLine:"Objevujte kulturu Vratislavi",eyebrow:"Šestý produkt Wroc-love",title:"Kulturní<br>dobrodružství.",lead:"Muzea, umění, divadlo, hudba, film a architektura — vyberte oblast a sestavte si vlastní návštěvu.",places:"míst",fiveLanguages:"Pět jazyků",directNavigation:"Přímá navigace",questionLabel:"Žádná povinná trasa",question:"Co vás dnes zajímá?",questionHint:"Vyberte oblast; mapa ukáže vhodná místa a umožní je volně kombinovat.",explore:"Objevujte podle oblasti",mapTitle:"Mapa kultury",searchLabel:"Hledat místa",searchPlaceholder:"Hledejte místo nebo oblast…",all:"Vše",museumsHistory:"Muzea a historie",artContemporary:"Současné umění",theatre:"Divadlo a performance",musicOpera:"Hudba a opera",film:"Film",architectureDesign:"Architektura a design",streetArt:"Street art",mapNote:"Mapa se přiblíží k výsledkům. Street art je označen dvěma oblastními body: Nadodrze a Ołbin.",allPlaces:"Všechna místa a zážitky",emptyTitle:"Žádná shoda",emptyText:"Zkuste jiné hledání nebo zobrazte vše.",showAll:"Zobrazit vše",livingGuide:"Živý, průběžně rozšiřovaný průvodce",editorialTitle:"Ne pevná trasa. Kulturní sbírka pro sestavení vlastního dne.",editorialText:"Každá karta používá kanonické místo a odkazuje na oficiální web a navigaci. Street art je zážitek ze čtvrtí se dvěma oblastními body.",homeReturn:"Zpět na hlavní stránku",communityLine:"Od komunity Wrocław & Dolní Slezsko",facebookGroup:"Skupina na Facebooku",facebookPage:"Firemní stránka",instagram:"Instagram",navigate:"Navigovat",officialWebsite:"Oficiální web",photos:"Fotografie",videos:"Video",resultOne:"výsledek",resultMany:"výsledků",areaExperience:"Oblastní zážitek"}
  };

  const places = Array.isArray(window.WROC_CULTURAL_PLACES) ? window.WROC_CULTURAL_PLACES : [];
  const experiences = Array.isArray(window.WROC_CULTURAL_EXPERIENCES) ? window.WROC_CULTURAL_EXPERIENCES : [];
  const symbols = {"museums-history":"🏛","art-contemporary":"◐","theatre-performing-arts":"◭","music-opera":"♫",film:"▶","architecture-design":"◇","street-art":"✺"};
  const labels = {"museums-history":"museumsHistory","art-contemporary":"artContemporary","theatre-performing-arts":"theatre","music-opera":"musicOpera","architecture-design":"architectureDesign","street-art":"streetArt"};
  const map = L.map("lifestyle-map", { scrollWheelZoom:false, zoomControl:true }).setView([51.1088,17.0335], 13);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {maxZoom:19, attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
  const markerLayer = L.layerGroup().addTo(map);
  const markers = new Map();
  const local = (value) => value && typeof value === "object" ? (value[language] || value.en || value.he || Object.values(value)[0]) : (value || "");
  const tr = (key) => ui[language]?.[key] || ui.en[key] || key;
  const esc = (value) => String(value || "").replace(/[&<>'"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
  const canonical = (item) => item?.canonicalPlace || window.WROC_CATALOG?.getPlace(item?.canonicalPlaceId || item?.id);
  const name = (item) => local(canonical(item)?.name || item.name) || canonical(item)?.localName || item.id;
  const searchable = (item) => [name(item), canonical(item)?.localName, local(canonical(item)?.description || item.description), ...item.categories.map((c)=>tr(labels[c]||c))].join(" ").toLocaleLowerCase();
  const currentResults = () => [...places,...experiences].filter((item)=>(activeCategory==="all"||item.categories.includes(activeCategory))&&(!searchTerm||searchable(item).includes(searchTerm)));

  function actionHtml(item) {
    const place=canonical(item); if(!place) return `<span class="place-note">${tr("areaExperience")}</span>`;
    const actions=[]; const maps=place.links?.navigation?.googleMaps||`https://www.google.com/maps/search/?api=1&query=${place.location.coordinates.lat}%2C${place.location.coordinates.lng}`;
    actions.push(`<a href="${esc(maps)}" target="_blank" rel="noopener"><span class="brand-icon media">↗</span>${tr("navigate")}</a>`);
    if(place.links?.website) actions.push(`<a href="${esc(place.links.website)}" target="_blank" rel="noopener"><span class="brand-icon media">◎</span>${tr("officialWebsite")}</a>`);
    for(const social of place.socialPosts||[]) actions.push(`<a href="${esc(social.url)}" target="_blank" rel="noopener"><span class="brand-icon ${social.platform}">${social.platform==="facebook"?"f":"◎"}</span>${social.platform==="facebook"?"Facebook":"Instagram"}</a>`);
    if(place.media?.photos?.length) actions.push(`<button type="button" data-gallery="${esc(item.id)}"><span class="brand-icon media">▣</span>${tr("photos")}</button>`);
    if(place.media?.videos?.length) actions.push(`<button type="button" data-video="${esc(item.id)}"><span class="brand-icon media">▶</span>${tr("videos")}</button>`);
    return actions.join("");
  }
  const tagsHtml=(item)=>item.categories.map((c)=>`<span class="place-tag eat">${symbols[c]||"✦"} ${esc(tr(labels[c]||c))}</span>`).join("");
  function cardHtml(item){const place=canonical(item);return `<article class="place-card${selectedId===item.id?" selected":""}" data-place="${esc(item.id)}" tabindex="0"><div class="place-topline"><h3>${esc(name(item))}</h3><div class="place-tags">${tagsHtml(item)}</div></div>${place?.localName&&place.localName!==name(item)?`<p class="local-name">${esc(place.localName)}</p>`:""}<p>${esc(local(place?.description||item.description))}</p>${item.placeType==="area-experience"?`<p class="place-note">${tr("areaExperience")}</p>`:""}<div class="place-actions">${actionHtml(item)}</div></article>`;}
  const popupHtml=(item,point)=>`<strong>${esc(name(item))}${point?.label?` — ${esc(point.label)}`:""}</strong><br><span>${esc(local(canonical(item)?.description||item.description))}</span><div class="place-actions">${actionHtml(item)}</div>`;
  function markerIcon(item){const c=activeCategory!=="all"?activeCategory:item.categories[0];return L.divIcon({className:"",html:`<span class="lifestyle-marker eat"><span>${symbols[c]||"✦"}</span></span>`,iconSize:[34,34],iconAnchor:[17,17],popupAnchor:[0,-18]});}
  function mapPointsFor(item){if(Array.isArray(item.mapPoints)&&item.mapPoints.length)return item.mapPoints.filter((point)=>Array.isArray(point.coordinates));return Array.isArray(item.coordinates)?[{id:item.id,coordinates:item.coordinates}]:[];}
  function fit(items){const points=items.flatMap(mapPointsFor);if(!points.length)return;if(points.length===1)map.setView(points[0].coordinates,16,{animate:true});else map.fitBounds(L.latLngBounds(points.map((point)=>point.coordinates)),{padding:[42,42],maxZoom:15,animate:true});}
  function render({fitMap=true}={}){const items=currentResults();markerLayer.clearLayers();markers.clear();items.forEach((item)=>mapPointsFor(item).forEach((point)=>{const marker=L.marker(point.coordinates,{icon:markerIcon(item),title:point.label?`${name(item)} — ${point.label}`:name(item)}).bindPopup(popupHtml(item,point),{maxWidth:340});marker.on("click",()=>select(item.id,false));marker.addTo(markerLayer);const itemMarkers=markers.get(item.id)||[];itemMarkers.push(marker);markers.set(item.id,itemMarkers);}));const list=document.getElementById("place-results");list.innerHTML=items.map(cardHtml).join("");list.hidden=!items.length;document.getElementById("empty-state").hidden=Boolean(items.length);document.getElementById("results-count").textContent=`${items.length} ${items.length===1?tr("resultOne"):tr("resultMany")}`;document.getElementById("results-title").textContent=activeCategory==="all"?tr("allPlaces"):tr(labels[activeCategory]||activeCategory);if(fitMap)fit(items);}
  function select(id,open=true){selectedId=id;document.querySelectorAll(".place-card").forEach((c)=>c.classList.toggle("selected",c.dataset.place===id));const marker=markers.get(id)?.[0];if(marker){map.panTo(marker.getLatLng(),{animate:true});if(open)marker.openPopup();}}
  function applyLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==="he"?"rtl":"ltr";document.title=`${tr("title").replace(/<br>/g," ")} | Wroc-love`;localStorage.setItem("wroclaw24-language",language);document.querySelectorAll("[data-i18n]").forEach((el)=>{const v=tr(el.dataset.i18n);if(el.dataset.i18n==="title")el.innerHTML=v;else el.textContent=v;});document.querySelectorAll("[data-i18n-placeholder]").forEach((el)=>el.placeholder=tr(el.dataset.i18nPlaceholder));document.querySelectorAll("[data-lang]").forEach((b)=>{const on=b.dataset.lang===language;b.classList.toggle("active",on);b.setAttribute("aria-pressed",String(on));});document.querySelectorAll("[data-home-link]").forEach((a)=>a.href=`/?lang=${language}`);const u=new URL(location.href);u.searchParams.set("lang",language);history.replaceState({},"",u);render({fitMap:false});}
  function openMedia(id,type){const item=places.find((p)=>p.id===id),place=canonical(item);if(!place)return;const modal=document.getElementById("media-modal"),content=document.getElementById("media-content");document.getElementById("media-title").textContent=name(item);content.innerHTML=type==="gallery"?`<div class="media-grid">${place.media.photos.map((src)=>`<img src="${esc(src)}" alt="${esc(name(item))}" loading="lazy">`).join("")}</div>`:`<div class="media-grid">${place.media.videos.map((src)=>`<video controls playsinline preload="metadata" src="${esc(typeof src==="string"?src:src.src)}"></video>`).join("")}</div>`;modal.hidden=false;modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";}
  function closeMedia(){const modal=document.getElementById("media-modal");modal.hidden=true;modal.setAttribute("aria-hidden","true");modal.querySelectorAll("video").forEach((v)=>v.pause());document.body.style.overflow="";}

  const accessState=await window.WROC_CAMPAIGN_ACCESS?.authorize(language);if(accessState&&!accessState.allowed)return;
  document.getElementById("place-count").textContent=String(places.length);
  document.querySelectorAll("[data-count]").forEach((el)=>{const c=el.dataset.count;el.textContent=c==="all"?places.length+experiences.length:[...places,...experiences].filter((p)=>p.categories.includes(c)).length;});
  document.querySelector(".category-filters").addEventListener("click",(event)=>{const button=event.target.closest("button[data-category]");if(!button)return;activeCategory=button.dataset.category;selectedId=null;document.querySelectorAll("button[data-category]").forEach((b)=>b.classList.toggle("active",b===button));render();});
  document.getElementById("place-search").addEventListener("input",(event)=>{searchTerm=event.target.value.trim().toLocaleLowerCase();selectedId=null;render();});
  document.getElementById("place-results").addEventListener("click",(event)=>{const gallery=event.target.closest("[data-gallery]"),video=event.target.closest("[data-video]");if(gallery){openMedia(gallery.dataset.gallery,"gallery");return;}if(video){openMedia(video.dataset.video,"video");return;}const card=event.target.closest("[data-place]");if(card)select(card.dataset.place);});
  document.getElementById("lifestyle-map").addEventListener("click",(event)=>{const gallery=event.target.closest("[data-gallery]"),video=event.target.closest("[data-video]");if(gallery){openMedia(gallery.dataset.gallery,"gallery");return;}if(video)openMedia(video.dataset.video,"video");});
  document.getElementById("reset-search").addEventListener("click",()=>{searchTerm="";activeCategory="all";document.getElementById("place-search").value="";document.querySelectorAll("button[data-category]").forEach((b)=>b.classList.toggle("active",b.dataset.category==="all"));render();});
  document.querySelectorAll("[data-lang]").forEach((button)=>button.addEventListener("click",()=>{if(supported.includes(button.dataset.lang)){language=button.dataset.lang;applyLanguage();}}));
  document.querySelector("[data-close-media]").addEventListener("click",closeMedia);document.getElementById("media-modal").addEventListener("click",(event)=>{if(event.target.id==="media-modal")closeMedia();});document.addEventListener("keydown",(event)=>{if(event.key==="Escape")closeMedia();});
  applyLanguage();render();setTimeout(()=>map.invalidateSize(),120);
})();
